export const RECIEVE_CARDS_LIST = 'RECIEVE_CARDS_LIST';

export const ADD_TO_CARDS_LIST = 'ADD_TO_CARDS_LIST';
export const UPDATE_CARDS_LIST = 'UPDATE_CARDS_LIST'

export const REMOVE_FROM_CARDS_LIST = 'REMOVE_FROM_CARDS_LIST'